[package]
name = "hugo2zola"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
clap = "3.0.5"
regex = "1"
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0"
serde_with = "1.11.0"
serde_yaml = "0.8"
tera = "1.15.0"
toml = "0.5"
